### ISSUE TITLE
Updating a plugin

### ISSUE THREAD

**Issue by tessus** [fengqiaozhu/joplin_plugin_nlr#1]
Please note that if you publish a new version, you should bump the patch level, minor, or major.

This is done in 2 files:

```
package.json
src/manifest.json
```

I'm only mentioning it, because I saw that something changed after the initial release but the version stayed the same.

https://github.com/joplin/plugins/commit/2c0f748d5c65941c66d251f513a20669b8d67b7b

**Comment by fengqiaozhu** [comment]
> Please note that if you publish a new version, you should bump the patch level, minor, or major.
> 
> This is done in 2 files:
> 
> ```
> package.json
> src/manifest.json
> ```
> 
> I'm only mentioning it, because I saw that something changed after the initial release but the version stayed the same.
> 
> [joplin/plugins@2c0f748](https://github.com/joplin/plugins/commit/2c0f748d5c65941c66d251f513a20669b8d67b7b)



> Please note that if you publish a new version, you should bump the patch level, minor, or major.
> 
> This is done in 2 files:
> 
> ```
> package.json
> src/manifest.json
> ```
> 
> I'm only mentioning it, because I saw that something changed after the initial release but the version stayed the same.
> 
> [joplin/plugins@2c0f748](https://github.com/joplin/plugins/commit/2c0f748d5c65941c66d251f513a20669b8d67b7b)

I've fixed it by publishing a new version, it's my mistake.

**Comment by tessus** [comment]
No worries. All good. It's just something I have noticed.
